# FROM mcr.microsoft.com/dotnet/runtime:6.0.7
# FROM gcr.io/google-appengine/aspnetcore:3.1
FROM mcr.microsoft.com/dotnet/sdk:6.0
COPY . /app
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_URLS=http://*:8080
ENTRYPOINT ["dotnet", "AzureADWeb.dll"]

# FROM gcr.io/google-appengine/aspnetcore:6
# COPY . /app
# WORKDIR /app
# ENTRYPOINT ["dotnet", "AzureADWeb.dll"]
